### ISSUE TITLE
[rojak-database] [bug] Error on populate dummy data (Schema v0.5)

### ISSUE THREAD

**Issue by bobbypriambodo** [pyk/rojak#179]
Reproduce:

```
$ mysql -u root -h 127.0.0.1 -p
> DROP DATABASE rojak_database;
Query OK, 7 rows affected (0.13 sec)
> CREATE DATABASE rojak_database;
Query OK, 1 row affected (0.00 sec)

$ mysql -u root -h 127.0.0.1 rojak_database < rojak_schema_latest.sql

$ ROJAK_DB_HOST=127.0.0.1 ROJAK_DB_PASS= sh populate_rojak_database_with_dummy_data.sh
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")
Traceback (most recent call last):
  File "generate_news_data.py", line 98, in <module>
    sentiment_i = random.randint(0, total_sentiment-1)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
```

**Comment by bobbypriam** [comment]
Masih dapet multiple `Something went wrong: (1054, "Unknown column 'candidate_id' in 'field list'")` error di `python generate_news_data.py` mas 😅

**Comment by pyk** [comment]
oops, forgot to update the dummy data generator

**Comment by pyk** [comment]
@bobbypriambodo For now you can use this:

```
# Insert candidate, pair of candidates and sentiment data
python insert_candidate_data.py

# Generate media data
python generate_media_data.py

# Generate news data, sentiment and mention data
python generate_news_data.py
```
