### ISSUE TITLE
[rojak-pantau] Detikcom spider issue?

### ISSUE THREAD

**Issue by girikuncoro** [pyk/rojak#42]
Barusan cobain jalanin ini `scrapy crawl detikcom` tapi ada eror.
Ini eror di komputerku saja atau di yang lain juga ya?

Sepertinya di komputerku start url ini http://news.detik.com/indeksfokus/67/jakarta-memilih/1 isinya kosong/blank, makanya cursor jadi `null` dan line 50 (https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L50) error.

Abaikan kalo ini bukan issue di yang lain.

```
2016-10-10 10:48:02 [scrapy] INFO: Scrapy 1.2.0 started (bot: rojak_pantau)
2016-10-10 10:48:02 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'rojak_pantau.spiders', 'SPIDER_MODULES': ['rojak_pantau.spiders'], 'ROBOTSTXT_OBEY': True, 'USER_AGENT': 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1', 'BOT_NAME': 'rojak_pantau'}
2016-10-10 10:48:03 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-10-10 10:48:03 [detikcom] INFO: Fetching media information
Unhandled error in Deferred:
2016-10-10 10:48:03 [twisted] CRITICAL: Unhandled error in Deferred:


Traceback (most recent call last):
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 163, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/rojak_pantau/spiders/detikcom.py", line 68, in from_crawler
    *args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/rojak_pantau/spiders/detikcom.py", line 50, in __init__
    self.media['id'] = row[0]
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
2016-10-10 10:48:03 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/crawler.py", line 94, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/rojak_pantau/spiders/detikcom.py", line 68, in from_crawler
    *args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/venv/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/rojak_pantau/spiders/detikcom.py", line 50, in __init__
    self.media['id'] = row[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pyk** [comment]
@girikuncoro oh ini

```
 File "/Users/gkuncoro/Hacks/rojak/rojak-pantau/rojak_pantau/spiders/detikcom.py", line 50, in __init__
    self.media['id'] = row[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

gara2 waktu [request informasi media ke database](https://github.com/pyk/rojak/blob/master/rojak-pantau/rojak_pantau/spiders/detikcom.py#L48) gak ada media yg namanya `detikcom`.

dikomputernya udah setup MySQL db sama insert `rojak-database/data_media.json` lewat `python insert_media_data.py` ?

**Comment by girikuncoro** [comment]
@pyk ah baiklah dicoba dulu, MySQL db baru `populate_rojak_database_with_dummy_data.sh` doang

**Comment by girikuncoro** [comment]
Oke aman, close ya

```
2016-10-10 11:43:58 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 29299,
 'downloader/request_count': 65,
 'downloader/request_method_count/GET': 65,
 'downloader/response_bytes': 417279,
 'downloader/response_count': 65,
 'downloader/response_status_count/200': 33,
 'downloader/response_status_count/302': 30,
 'downloader/response_status_count/404': 2,
 'dupefilter/filtered': 10,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 10, 10, 18, 43, 58, 659990),
 'item_scraped_count': 30,
 'log_count/DEBUG': 97,
 'log_count/ERROR': 1,
 'log_count/INFO': 114,
 'request_depth_max': 2,
 'response_received_count': 35,
 'scheduler/dequeued': 63,
 'scheduler/dequeued/memory': 63,
 'scheduler/enqueued': 63,
 'scheduler/enqueued/memory': 63,
 'spider_exceptions/IndexError': 1,
 'start_time': datetime.datetime(2016, 10, 10, 18, 43, 52, 844793)}
2016-10-10 11:43:58 [scrapy] INFO: Spider closed (finished)
```

**Comment by pyk** [comment]
@girikuncoro oke mas 🙇
